### ISSUE TITLE
Create DFD

### ISSUE THREAD

**Issue by kla587** [kla587/Internet-System-Dev#12]

**Comment by kla587** [comment]
Created first draft on 2/15

**Comment by kla587** [comment]
![dfd](https://cloud.githubusercontent.com/assets/16999040/13271274/997571c8-da59-11e5-93ce-7d2d67e96dda.PNG)

**Comment by kla587** [comment]
![dfdv2](https://cloud.githubusercontent.com/assets/16999040/13271521/15aab73e-da5b-11e5-9612-15f7f5d4cfbd.PNG)

**Comment by kla587** [comment]
![dfd3](https://cloud.githubusercontent.com/assets/16999040/13272476/fcaf23ee-da61-11e5-80d2-31282ffcf6da.PNG)

**Comment by kla587** [comment]
![dfdv4](https://cloud.githubusercontent.com/assets/16999040/13272895/11d620c6-da65-11e5-8b6a-1596c665dccb.PNG)

**Comment by kla587** [comment]
![dfdv5](https://cloud.githubusercontent.com/assets/16999040/13273022/12b4e62a-da66-11e5-8c87-25c81d1d7396.PNG)

**Comment by kla587** [comment]
![image](https://cloud.githubusercontent.com/assets/16999040/13306180/061da980-db27-11e5-896d-c9a637471d3f.png)

**Comment by kla587** [comment]
![dfd jpg](https://cloud.githubusercontent.com/assets/16999040/13802441/f2758c98-eb09-11e5-9924-fe9153a9e6a5.png)

**Comment by kla587** [comment]
![dfd](https://cloud.githubusercontent.com/assets/16999040/13802443/feacd200-eb09-11e5-9834-f9d47a4db1f9.jpg)

**Comment by kla587** [comment]
![dfd diagram](https://cloud.githubusercontent.com/assets/16999040/13802455/1ae4e82c-eb0a-11e5-9108-6ac9918ba844.png)

**Comment by kla587** [comment]
![dfd diagram](https://cloud.githubusercontent.com/assets/16999040/13802468/413ed47e-eb0a-11e5-9b46-60d9177057b9.png)

**Comment by kla587** [comment]
![dfd diagramv2](https://cloud.githubusercontent.com/assets/16999040/13827518/e8709da6-eb8a-11e5-9101-9771e458876d.png)

**Comment by Faisal2016** [comment]
Done.
