### ISSUE TITLE
Create DFD # 1

### ISSUE THREAD

**Issue by Doneroger** [kla587/Internet-System-Dev#15]
[https://drive.google.com/open?id=0B3MR](url)

**Comment by Doneroger** [comment]
Hello Mikayla, Faisal, Aayush

Here is the DFD Diagram. I cannot  read some words, so you just have to double-click on the line to add a  word. I will also send you the picture I took in the case you will need it to add the missing words.

Thank you,

[https://drive.google.com/open?id=0B3MR](url)

Donatien

**Comment by kla587** [comment]
Hey guys,

Sorry for the last minuet note, I will not make it class today. I have a
capstone meeting with our client this afternoon and it was the only time
that worked. Let's plan to meet sometime this week to work on source code.

What works for everyone?

Thanks,

Mikayla
