### ISSUE TITLE
Adding Images to Repo

### ISSUE THREAD

**Issue by kla587** [kla587/Internet-System-Dev#18]
Good instructions for adding images:

http://solutionoptimist.com/2013/12/28/awesome-github-tricks/

**Comment by kla587** [comment]
![dfd](https://cloud.githubusercontent.com/assets/16999040/13761170/fd55f59a-ea04-11e5-92ab-1fc63b1249c4.jpg)

**Comment by kla587** [comment]
Better Instructions:

http://felixhayashi.github.io/ReadmeGalleryCreatorForGitHub/

**Comment by Faisal2016** [comment]
Done.
