### ISSUE TITLE
Use Case

### ISSUE THREAD

**Issue by Doneroger** [kla587/Internet-System-Dev#22]
Title: Users makes commit subject to existing SPDX data of project
Primary Actor: Users
Goal in Context: To indicate the plugin has received the POM files to be sent to Maven
Preconditions:
The POM files must be XML files
Plugin has received the Pom files
Stakeholders and Interests:
1. User:
To know the dependencies that the POM files contain
2. Plugin:
To Host the POM files to be sent to Maven
3. Maven:
To parse the POM files for dependencies
1. DoSOCS
           To Generate a report
           To place the package in SPDX database while keeping the dependency hierarchies
   Main Success Scenario: Users received back at least one dependency from Maven scanning
   Failed End Condition:
   Maven return no dependencies while the package contains dependencies.

Trigger:
        Commit of code to an upstream POM
Notes:

**Comment by Faisal2016** [comment]
Done.
