### ISSUE TITLE
New License Declaration

### ISSUE THREAD

**Issue by germonprez** [kla587/Internet-System-Dev#26]
Fix this: 
The license under which the WordPress software is released is the GPLv2 (or later) from the Free Software Foundation. A copy of the license is included with every copy of WordPress

https://wordpress.org/about/license/

Should be: 
Pointed to: https://spdx.org/licenses/GPL-2.0.html

Text should be: Licensed under GPLv2

**Comment by Faisal2016** [comment]
We remove one of the license so, now we have one license for our repo.

**Comment by Faisal2016** [comment]
Can I close the issue?!
Or there are any  other comments.

**Comment by kla587** [comment]
Deleted other license. Okay to close.
