### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by tpflueger** [kla587/Internet-System-Dev#28]
Running a small dependency tree of around 5 nodes took a considerably long time. I'm not entirely sure if its just my machine or other issues.

**Comment by Ayy-ay-oos** [comment]
Currently looking at enhancing the performance of our code

**Comment by kla587** [comment]
The POM we had was rather large. Testing with another POM to see if I can duplicate your results.

**Comment by kla587** [comment]
The application still take a long time to run, but will not be able to fix at this time.
